# Heurísticas para o problema de caminho mais curto (ou mínimo)


# Problema - trajeto de carro (consultora)

In [ ]:
import numpy as np

In [ ]:
vertices = {'Ponta-Grossa(PR)': 0, 'Arapoti(PR)': 1, 'Sao-Paulo(SP)': 2, 'Curitiba(PR)': 3, 'Guarapuava(PR)': 4,
            'Bituruna(PR)': 5, 'Uniao-da-Vitoria(PR)': 6, 'Cacador(SC)': 7, 'Ponte-Alta-do-Norte(SC)': 8, 'Canoinhas(SC)': 9,
            'Jaragua-do-Sul(SC)': 10, 'Pomerode(SC)': 11, 'Blumenau(SC)': 12, 'Gaspar(SC)': 13}

In [ ]:
vertices['Ponta-Grossa(PR)'], vertices['Jaragua-do-Sul(SC)'], vertices['Bituruna(PR)']

(0, 10, 5)

In [ ]:
len(vertices)

14

In [ ]:
cidades = {0: 'Ponta-Grossa(PR)', 1: 'Arapoti(PR)', 2: 'Sao-Paulo(SP)', 3: 'Curitiba(PR)', 4: 'Guarapuava(PR)',
           5: 'Bituruna(PR)', 6: 'Uniao-da-Vitoria(PR)', 7: 'Cacador(SC)', 8: 'Ponte-Alta-do-Norte(SC)', 9: 'Canoinhas(SC)',
           10: 'Jaragua-do-Sul(SC)', 11: 'Pomerode(SC)', 12: 'Blumenau(SC)', 13: 'Gaspar(SC)'}

In [ ]:
cidades[0], cidades[12]

('Ponta-Grossa(PR)', 'Blumenau(SC)')

In [ ]:
arestas = np.zeros([len(cidades), len(cidades)], dtype=int)

In [ ]:
arestas.shape

(14, 14)

In [ ]:
arestas

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
vertices['Ponta-Grossa(PR)'], vertices['Arapoti(PR)'], vertices['Curitiba(PR)'], vertices['Guarapuava(PR)']

(0, 1, 3, 4)

In [ ]:
arestas[vertices['Ponta-Grossa(PR)'], [vertices['Arapoti(PR)']]] = 136
arestas[vertices['Ponta-Grossa(PR)'], [vertices['Curitiba(PR)']]] = 114
arestas[vertices['Ponta-Grossa(PR)'], [vertices['Guarapuava(PR)']]] = 131

In [ ]:
arestas[vertices['Arapoti(PR)'],[vertices['Ponta-Grossa(PR)']]] = 136
arestas[vertices['Arapoti(PR)'],[vertices['Sao-Paulo(SP)']]] = 416

arestas[vertices['Sao-Paulo(SP)'],[vertices['Arapoti(PR)']]] = 416
arestas[vertices['Sao-Paulo(SP)'],[vertices['Curitiba(PR)']]] = 404

arestas[vertices['Curitiba(PR)'],[vertices['Sao-Paulo(SP)']]] = 404
arestas[vertices['Curitiba(PR)'],[vertices['Ponta-Grossa(PR)']]] = 114
arestas[vertices['Curitiba(PR)'],[vertices['Pomerode(SC)']]] = 214
arestas[vertices['Curitiba(PR)'],[vertices['Canoinhas(SC)']]] = 178

arestas[vertices['Guarapuava(PR)'],[vertices['Ponta-Grossa(PR)']]] = 131
arestas[vertices['Guarapuava(PR)'],[vertices['Bituruna(PR)']]] = 72

arestas[vertices['Bituruna(PR)'],[vertices['Guarapuava(PR)']]] = 72
arestas[vertices['Bituruna(PR)'],[vertices['Uniao-da-Vitoria(PR)']]] = 80

arestas[vertices['Uniao-da-Vitoria(PR)'],[vertices['Bituruna(PR)']]] = 80
arestas[vertices['Uniao-da-Vitoria(PR)'],[vertices['Cacador(SC)']]] = 90

arestas[vertices['Cacador(SC)'],[vertices['Uniao-da-Vitoria(PR)']]] = 90
arestas[vertices['Cacador(SC)'],[vertices['Ponte-Alta-do-Norte(SC)']]] = 100

arestas[vertices['Ponte-Alta-do-Norte(SC)'],[vertices['Cacador(SC)']]] = 100
arestas[vertices['Ponte-Alta-do-Norte(SC)'],[vertices['Jaragua-do-Sul(SC)']]] = 243
arestas[vertices['Ponte-Alta-do-Norte(SC)'],[vertices['Canoinhas(SC)']]] = 144

arestas[vertices['Canoinhas(SC)'],[vertices['Ponte-Alta-do-Norte(SC)']]] = 144
arestas[vertices['Canoinhas(SC)'],[vertices['Curitiba(PR)']]] = 178
arestas[vertices['Canoinhas(SC)'],[vertices['Jaragua-do-Sul(SC)']]] = 229

arestas[vertices['Pomerode(SC)'],[vertices['Curitiba(PR)']]] = 214
arestas[vertices['Pomerode(SC)'],[vertices['Blumenau(SC)']]] = 30

arestas[vertices['Jaragua-do-Sul(SC)'],[vertices['Canoinhas(SC)']]] = 229
arestas[vertices['Jaragua-do-Sul(SC)'],[vertices['Ponte-Alta-do-Norte(SC)']]] = 243
arestas[vertices['Jaragua-do-Sul(SC)'],[vertices['Blumenau(SC)']]] = 67

arestas[vertices['Blumenau(SC)'],[vertices['Pomerode(SC)']]] = 30
arestas[vertices['Blumenau(SC)'],[vertices['Jaragua-do-Sul(SC)']]] = 67
arestas[vertices['Blumenau(SC)'],[vertices['Gaspar(SC)']]] = 19

In [ ]:
arestas[vertices['Jaragua-do-Sul(SC)'],[vertices['Canoinhas(SC)']]]

array([229])

In [ ]:
arestas[vertices['Ponta-Grossa(PR)'],[vertices['Curitiba(PR)']]]

array([114])

## Algoritmo de Dijkstra

In [ ]:
cidades[1]

'Arapoti(PR)'

In [ ]:
import sys
sys.maxsize

9223372036854775807

In [ ]:
[sys.maxsize] * 14

[9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807,
 9223372036854775807]

In [ ]:
[False] * 14

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [ ]:
import sys
class Dijkstra:
  def __init__(self, vertices, arestas, inicio):
    self.tamanho = len(vertices)
    self.vertices = vertices
    self.grafo = arestas
    self.inicio = inicio

  def mostra_solucao(self, distancias):
    print('Os trajetos mais curtos em relação à {}, são:'.format(self.vertices[self.inicio]))
    for vertice in range(self.tamanho):
      #if distancias[vertice] > 0:
       print('\n{}: {}Km'.format(self.vertices[vertice], distancias[vertice]))
      #else:
        #print('\n---')


  def distancia_minima(self, distancia, visitados):
    minimo = sys.maxsize
    for vertice in range(self.tamanho):
      if distancia[vertice] < minimo and visitados[vertice] == False:
        minimo = distancia[vertice]
        indice_minimo = vertice
    return indice_minimo

  def dijkstra(self):
    distancia = [sys.maxsize] * self.tamanho
    distancia[self.inicio] = 0
    visitados = [False] * self.tamanho

    for _ in range(self.tamanho):
      indice_minimo = self.distancia_minima(distancia, visitados)
      visitados[indice_minimo] = True
      for vertice in range(self.tamanho):
        if self.grafo[indice_minimo][vertice] > 0 and visitados[vertice] == False \
            and distancia[vertice] > distancia[indice_minimo] + self.grafo[indice_minimo][vertice]:
          distancia[vertice] = distancia[indice_minimo] + self.grafo[indice_minimo][vertice]

    self.mostra_solucao(distancia)

In [ ]:
dijkstra = Dijkstra(cidades, arestas, vertices['Ponta-Grossa(PR)'])
dijkstra.dijkstra()

Os trajetos mais curtos em relação à Ponta-Grossa(PR), são:

Ponta-Grossa(PR): 0Km

Arapoti(PR): 136Km

Sao-Paulo(SP): 518Km

Curitiba(PR): 114Km

Guarapuava(PR): 131Km

Bituruna(PR): 203Km

Uniao-da-Vitoria(PR): 283Km

Cacador(SC): 373Km

Ponte-Alta-do-Norte(SC): 436Km

Canoinhas(SC): 292Km

Jaragua-do-Sul(SC): 425Km

Pomerode(SC): 328Km

Blumenau(SC): 358Km

Gaspar(SC): 377Km
